USE tango;

CREATE TABLE `tango`.`CPA50` (
  `ID_CPA50` INTEGER UNSIGNED NOT NULL,
  `FILLER` VARCHAR(20),
  `COD_COMPRA` VARCHAR(3) NOT NULL,
  `NOM_COMPRA` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID_CPA50`)
)
ENGINE = InnoDB
COMMENT = 'Replica de la tabla CPA50';